name: Pulumi preview
on:
  - pull_request
jobs:
  preview:
    permissions:
      pull-requests: write
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set up Python
        run: cd pulumi-test1 && uv python install
      - name: Install dependencies
        run: cd pulumi-test1 && uv sync
      - uses: pulumi/actions@v6
        with:
          command: preview
          comment-on-pr: true
          stack-name: dev
          github-token: ${{ secrets.GITHUB_TOKEN }}
          work-dir: pulumi-test1
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
